### ISSUE TITLE
Issues report, features request and UI/UX suggestions

### ISSUE THREAD

**Issue by jahirfiquitiva** [TeamAmaze/AmazeFileManager#298]
Hi

First of all, thanks for this awesome explorer. I like the things it has, and how well designed it is.

Anyways, I would like to suggest and request some things. I didn't want to make a post for each thing as they will be kinda many.

Let's start:
#### 1. When selecting items, toolbar should keep the primary color (in my case it should be blue), and that teal little bar should disappear.
<img src="https://cloud.githubusercontent.com/assets/10360816/17236884/41ea7d84-5512-11e6-9575-de18ad7e5dca.png" height="300px"/>

#### 2. The bar where the path text appears is a bit too big, please reduce its height to be the same as toolbar (56 dp) and/or add an option to hide it (as MK explorer).
<img src="https://cloud.githubusercontent.com/assets/10360816/17236905/789aab92-5512-11e6-983a-4b285549c227.png" height="300px"/>

#### 3. Don't make Floating Action Menu labels full black, make them dark grey instead. Like [this](https://github.com/futuresimple/android-floating-action-button/blob/master/screenshots/labels.png). And add some shadow (elevation to them) like [here](https://lh3.googleusercontent.com/mp79J0Gsfiobnb3zxvSq75Huyl-EBwdEc5cmTy7PW3tZg7VkmnD9L38FeXrasnGBuiM=h900-rw).
<img src="https://cloud.githubusercontent.com/assets/10360816/17236988/0fa48454-5513-11e6-9811-94cda0cb152e.png" height="300px"/>

#### 4. The back arrow in light theme is dark grey and looks bad over the grey circle, please make it white.
<img src="https://cloud.githubusercontent.com/assets/10360816/17237064/b38573da-5513-11e6-8b5d-6bd11cf12e54.png" height="300px"/>

#### 5. I think "Remove" option should be in this pop-up menu too, instead of just in selection toolbar.
<img src="https://cloud.githubusercontent.com/assets/10360816/17237072/c98d074c-5513-11e6-816b-7aebfac4f027.png" height="300px"/>

#### 6. After selection of these items in navigation drawer, they don't appear as selected.
<img src="https://cloud.githubusercontent.com/assets/10360816/17237075/d120dfd8-5513-11e6-8bce-54b73b1dde3f.png" height="300px"/>

#### 7. Documents icon is not from Material Design iconset. (I think is the only one not from there).
<img src="https://cloud.githubusercontent.com/assets/10360816/17237127/47d922f2-5514-11e6-894c-fa61bdcc1348.png" height="300px"/>

Please use [this icon](https://materialdesignicons.com/icon/file-document)

**Comment by jahirfiquitiva** [comment]
Glad to kinda help. Can't wait for them to be implemented. Thanks for the awesome app.

**Comment by jahirfiquitiva** [comment]
I just got an update and none of these things are fixed or implemented...

Are they going to simply be ignored? Or are they still in your plans?

😅

**Comment by vishal0071** [comment]
I'm focusing on functionality right now (Cloud/FTP). So these will come after that.

**Comment by jahirfiquitiva** [comment]
Ok thanks. Great work.... I'm still hopeful 😄🙂

**Comment by vishal0071** [comment]
I'm still not finding enough time for this, please have patience. I'm working on more important stuff for Amaze (:

**Comment by jahirfiquitiva** [comment]
@vishal0071 
If I help you with part of these... Would you mind publishing an update on PlayStore? I really want these things ...

**Comment by vishal0071** [comment]
1,4,5 had been fixed! I'll be glad if you help me fix the remaining! (:

**Comment by jahirfiquitiva** [comment]
@vishal0071

I will try. At least the most "annoying"

**Comment by EmmanuelMess** [comment]
2 should be solved, not really sure (it's weird).
8 has been solved in latest release candidate (3.1.2).
9 appears to have been solved.

**Comment by vishal0071** [comment]
Most of the things have been resolved I guess. Let us know if you still feel any of these should be fixed from v3.2.0

**Comment by EmmanuelMess** [comment]
3, 6, 7 haven't been solved.

**Comment by jahirfiquitiva** [comment]
2 Hasn't been fixed either.

Also, for 3, I would suggest using [this library](https://github.com/jahirfiquitiva/FABsMenu) (Totally not biased 😅)

**Comment by EmmanuelMess** [comment]
@jahirfiquitiva your library is not compatible with API 14...

**Comment by jahirfiquitiva** [comment]
@EmmanuelMess Sorry, I didn't expect people using a min sdk that low. You can use version [`1.0.9`](https://github.com/jahirfiquitiva/FABsMenu/releases/tag/1.0.9), I lowered the min sdk

**Comment by EmmanuelMess** [comment]
@jahirfiquitiva Well, you did help making this library :)

**Comment by jahirfiquitiva** [comment]
@EmmanuelMess 
Well, great 😁

**Comment by EmmanuelMess** [comment]
2 isn't fixed.

**Comment by VishalNehra** [comment]
For second, you can change it's height but don't make an option to disable it.

**Comment by trymeouteh** [comment]
I agree with #1. I don't care for the black toolbar when your selecting items.

**Comment by VishalNehra** [comment]
Most of the issues I see here have been solved with latest versions (:
